@NexoRuta.Api_HostAddress = http://localhost:5041
# Para Compose, usar http://localhost:5000 como HostAddress.
# Reemplazar por el acceso de una cuenta de comercio obtenido en GET /api/accesos.
@NexoRuta.AccesoId = 00000000-0000-0000-0000-000000000000

GET {{NexoRuta.Api_HostAddress}}/health/ready
Accept: application/json

###

GET {{NexoRuta.Api_HostAddress}}/api/accesos?tipo=Comercio
Accept: application/json

###

GET {{NexoRuta.Api_HostAddress}}/api/usuarios/actual
X-NexoRuta-Acceso: {{NexoRuta.AccesoId}}
Accept: application/json

###

GET {{NexoRuta.Api_HostAddress}}/api/operadores
X-NexoRuta-Acceso: {{NexoRuta.AccesoId}}
Accept: application/json

###

GET {{NexoRuta.Api_HostAddress}}/api/envios
X-NexoRuta-Acceso: {{NexoRuta.AccesoId}}
Accept: application/json

###
