// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexoRuta.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexoRuta.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NexoRutaDbContext))]
    [Migration("20261008231255_ShipmentCommerce")]
    partial class ShipmentCommerce
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexoRuta.Domain.Administracion.AccesoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ComercioId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EsPropietario")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ComercioId");

                    b.HasIndex("OperadorId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("AccesosUsuario", null, t =>
                        {
                            t.HasCheckConstraint("CK_AccesosUsuario_Pertenencia", "(\"OperadorId\" IS NULL) <> (\"ComercioId\" IS NULL)");

                            t.HasCheckConstraint("CK_AccesosUsuario_Propietario", "NOT \"EsPropietario\" OR \"ComercioId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("NexoRuta.Domain.Administracion.Comercio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.ToTable("Comercios", (string)null);
                });

            modelBuilder.Entity("NexoRuta.Domain.Administracion.Operador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.ToTable("Operadores", (string)null);
                });

            modelBuilder.Entity("NexoRuta.Domain.Administracion.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("NexoRuta.Domain.Envios.Bulto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AltoCentimetros")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("AnchoCentimetros")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("EnvioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LargoCentimetros")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PesoGramos")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId", "EnvioId");

                    b.ToTable("Bultos", (string)null);
                });

            modelBuilder.Entity("NexoRuta.Domain.Envios.Destinatario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Destinatarios", (string)null);
                });

            modelBuilder.Entity("NexoRuta.Domain.Envios.Direccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Direcciones", (string)null);
                });

            modelBuilder.Entity("NexoRuta.Domain.Envios.Envio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComercioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreadoPorUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DestinatarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DireccionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ComercioId");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("OperadorId", "DestinatarioId");

                    b.HasIndex("OperadorId", "DireccionId");

                    b.ToTable("Envios", (string)null);
                });

            modelBuilder.Entity("NexoRuta.Domain.Administracion.AccesoUsuario", b =>
                {
                    b.HasOne("NexoRuta.Domain.Administracion.Comercio", null)
                        .WithMany()
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexoRuta.Domain.Administracion.Operador", null)
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexoRuta.Domain.Administracion.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NexoRuta.Domain.Envios.Bulto", b =>
                {
                    b.HasOne("NexoRuta.Domain.Envios.Envio", null)
                        .WithMany()
                        .HasForeignKey("OperadorId", "EnvioId")
                        .HasPrincipalKey("OperadorId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NexoRuta.Domain.Envios.Destinatario", b =>
                {
                    b.HasOne("NexoRuta.Domain.Administracion.Operador", null)
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NexoRuta.Domain.Envios.Direccion", b =>
                {
                    b.HasOne("NexoRuta.Domain.Administracion.Operador", null)
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NexoRuta.Domain.Envios.Envio", b =>
                {
                    b.HasOne("NexoRuta.Domain.Administracion.Comercio", null)
                        .WithMany()
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexoRuta.Domain.Administracion.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexoRuta.Domain.Administracion.Operador", null)
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexoRuta.Domain.Envios.Destinatario", null)
                        .WithMany()
                        .HasForeignKey("OperadorId", "DestinatarioId")
                        .HasPrincipalKey("OperadorId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexoRuta.Domain.Envios.Direccion", null)
                        .WithMany()
                        .HasForeignKey("OperadorId", "DireccionId")
                        .HasPrincipalKey("OperadorId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
